pipeline{
   agent any

   parameters{
     string(name: 'deploy', defaultValue: 'default', description: 'Custom Deployment Name')
     choice(name: 'Zone', choices: ['EU-WEST-2A', 'EU-WEST-2B', 'EU-WEST-2C'], description: 'List of Zone')
     booleanParam(name: 'confirm', defaultValue: false, description: 'Toggle this value to confirm deployment')
   }
   
   stages{
    stage("Maven Test"){
      steps{  
       
         sh "mvn clean install"
         sh "mvn test"

       
      } 
    }
     
   }


}