{{- if .Values.autoscaler.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ template "fullname" . }}
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ .Values.replicasMax }}
  targetCPUUtilizationPercentage: {{ .Values.cpuTargetPercentage }}
{{- end }}
